title: Webcam Face-Mask Detector
email: pgmenon@andrew.cmu.edu 

js: p5.min.js, p5.dom.min.js, ml5.min.js, sketch.js

baseurl: "/SinglePerson_FaceMaskDetector" # the subpath of your site, e.g. /blog
url: "https://menonpg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: themedcave
github_username:  menonpg
linkedin_username: prahladmenon 

#remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

# Build settings
theme:  jekyll-theme-cayman 
#jekyll-theme-clean-blog
plugins:
  - jekyll-feed
