title: Webcam Face-Mask Detector
email: pgmenon@andrew.cmu.edu 

baseurl: "/SinglePerson_FaceMaskDetector" # the subpath of your site, e.g. /blog
url: "https://menonpg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: themedcave
github_username:  menonpg
linkedin_username: prahladmenon 

# Build settings
theme:  jekyll-theme-minimal 
#jekyll-theme-clean-blog
plugins:
  - jekyll-feed
